services:
  app:
    image: snipe/snipe-it:latest
    container_name: snipeit-app
    restart: unless-stopped
    volumes:
      - ./storage:/var/lib/snipeit
#      - ./storage/logs:/var/www/html/storage/logs
    ports:
      - "8009:80"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env

  db:
    image: mysql:5.7
    container_name: snipeit-db
    restart: unless-stopped
    volumes:
      - .db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10