services:
  activemq-artemis:
    image: apache/activemq-artemis:latest-alpine
    container_name: activemq-artemis
    ports:
      - "8161:8161" # Web Console
      - "61616:61616" # OpenWire
      - "5672:5672" # AMQP
      - "61613:61613" # STOMP
      - "5445:5445" # HORNETQ,STOMP
      - "1883:1883" # MQTT
      - "61614:61614" # WS
    environment:
      - ARTEMIS_USER=artemis
      - ARTEMIS_PASSWORD=artemis
      - ANNONYMOUS_LOGIN=false