services:
  activemq-artemis:
    image: apache/activemq-artemis:latest
    container_name: activemq-artemis
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      - ARTEMIS_USERNAME=admin
      - ARTEMIS_PASSWORD=password
      - ANNONYMOUS_LOGIN=false